name: repo-fix
url: https://gitdigital.app
hook_attributes:
  url: https://ai.gitdigital.app/github/webhook
redirect_url: https://gitdigital.app/apps/repo-fix/installed
public: false

default_permissions:
  contents: write
  metadata: read
  issues: write
  pull_requests: write
  checks: write

default_events:
  - push
  - pull_request
  - check_run
  - repository
  - issues
